from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from app.player.channels import Channel
from app.protocol import Command, NetflixContext, PointerActionMessage
from app.state import ActiveApp


class CommandExecutionError(RuntimeError):
    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message


class ApplicationPort(Protocol):
    async def open(self, app: ActiveApp) -> NetflixContext | None: ...
    async def open_news(self, url: str) -> None: ...
    async def search_youtube(self, query: str) -> None: ...

    async def return_home(self) -> None: ...
    async def leave_to_desktop(self) -> None: ...

    async def forward_command(self, command: Command) -> NetflixContext | None: ...
    async def type_text(
        self, text: str, submit: bool = False
    ) -> NetflixContext | None: ...

    def require_input_target(self, app: ActiveApp) -> None: ...



class PlayerPort(Protocol):
    async def open(self) -> tuple[int, str]: ...
    async def close(self) -> None: ...

    async def toggle_pause(self) -> None: ...

    async def next(self) -> None: ...

    async def previous(self) -> None: ...

    async def change_channel(self, direction: int) -> tuple[int, str]: ...


class VolumePort(Protocol):
    async def increase(self) -> tuple[int, bool]: ...

    async def decrease(self) -> tuple[int, bool]: ...

    async def toggle_mute(self) -> tuple[int, bool]: ...


class InputPort(Protocol):
    async def pointer(self, message: PointerActionMessage) -> None: ...

    async def text(self, text: str) -> None: ...


class PowerPort(Protocol):
    async def sleep(self) -> None: ...


class NewsPort(Protocol):
    @property
    def current(self) -> Channel: ...

    def move(self, direction: int) -> Channel: ...
